_target_: cdvae.pl_modules.decoderdenoiser.GemNetTDenoiserDecoder
hidden_dim: 256
latent_dim: ${model.latent_dim}  # Reference the main model's latent_dim
max_neighbors: 20
radius: 6.0
scale_file: ${oc.env:PROJECT_ROOT}/cdvae/pl_modules/gemnet/gemnet-dT.json
